// <auto-generated />
using IronForge.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IronForge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200921000115_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IronForge.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Barbells"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Plates"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Benches"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Racks"
                        });
                });

            modelBuilder.Entity("IronForge.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ImageThumbnailUrl = "~/Images/Olympic_Weightlifting_Bar.jpg",
                            ImageUrl = "~/Images/Olympic_Weightlifting_Bar.jpg",
                            InStock = true,
                            LongDescription = "Combining a stainless steel, 200,000 PSI tensile strength shaft with industrial hard chrome sleeves and quality needle bearings, this version of the Iron Forge Olympic Weightlifting Bar ranks among the best in the industry for feel, durability, and performance.",
                            Name = "OLYMPIC WEIGHTLIFTING BAR - STAINLESS STEEL",
                            Price = 450m,
                            ShortDescription = "OLYMPIC WEIGHTLIFTING BAR - STAINLESS STEEL"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            ImageThumbnailUrl = "~/Images/Power_Bar.jpg",
                            ImageUrl = "~/Images/Power_Bar.jpg",
                            InStock = true,
                            LongDescription = "   This is the premier power bar in the Iron Forge arsenal; equipped with a stainless steel shaft and sleeves for a superior feel and unmatched oxidation resistance. Includes a zero-flex 200,000 PSI tensile strength shaft, quality bronze bushings, and 16.25” of loadable sleeve length.",
                            Name = "POWER BAR - STAINLESS STEEL",
                            Price = 350m,
                            ShortDescription = "POWER BAR - STAINLESS STEEL"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            ImageThumbnailUrl = "~/Images/20KG_Competition_Plates.jpg",
                            ImageUrl = "~/Images/20KG_Competition_Plates.jpg",
                            InStock = true,
                            LongDescription = " KG Competition Plates are all a standard 450MM in diameter, with chrome-plated steel disc inserts and a 50.4MM collar opening for a firm, stable hold. The weight tolerance for each bumper is +/- 15 grams, and the average durometer rating of 94 ensures a minimal / dead bounce on the drop.",
                            Name = "20KG COMPETITION PLATES",
                            Price = 250m,
                            ShortDescription = "20KG COMPETITION PLATES"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3,
                            ImageThumbnailUrl = "~/Images/Weight_Bench.jpg",
                            ImageUrl = "~/Images/Weight_Bench.jpg",
                            InStock = true,
                            LongDescription = "  With more than 50 combinations of seat and back-rest positions to choose from, the Iron Forge Adjustable Bench can easily adapt to each individual athlete, improving the overall efficiency and productivity of any strength training facility. No matter your size, workout preferences, or available training space, this compact, 11-gauge steel bench provides the rare combination of sturdiness and maneuverability that few other adjustable weight benches even attempt to match. The Iron Forge Adjustable Bench includes six different seat settings and nine additional back rest positions, making it easily among the most versatile weight benches on the market.",
                            Name = "ADJUSTABLE BENCH",
                            Price = 800m,
                            ShortDescription = "ADJUSTABLE BENCH"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4,
                            ImageThumbnailUrl = "~/Images/Power_Rack.jpg",
                            ImageUrl = "~/Images/Power_Rack.jpg",
                            InStock = true,
                            LongDescription = "Iron Forge Power Rack is among the most versatile and customizable power racks in the industry. Each unit comes with standard  (6) 90” uprights, 5/8” bolts and fasteners, (2)  J-Cups, (2) pin/pipe safeties, (4) band pegs, (1) 43” single pull-up bar, and (8) plate storage posts for the back section of the unit. The laser-cut holes on each upright are spaced in the Westside pattern: 1” through bench and clean pull zone, 2” spacing above and below.",
                            Name = "POWER RACK",
                            Price = 1050m,
                            ShortDescription = "POWER RACK"
                        });
                });

            modelBuilder.Entity("IronForge.Models.Product", b =>
                {
                    b.HasOne("IronForge.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
